pluginManagement {
    repositories {
        maven { url 'https://maven.fabricmc.net/' }
		maven { url 'https://maven.kikugie.dev/releases' }
		mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "Iconic"

include (
	'iconic-base',
//	'iconic-custom-model-api',
//	'iconic-custom-item-animations',
	'iconic-construct-api',
	'iconic-splash-text-api',
)
